AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CodeDeploy Security Group"
Parameters:
  VPCID:
    Description: "VPC ID"
    Type: String
  MyIp:
    Description: "Enter your IP address in CIDR notation, e.g 100.150.200.225/32"
    Type: String
Resources:
  WebSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Web Security Group"
      SecurityGroupEgress:
      - CidrIp: "0.0.0.0/0"
        FromPort: -1
        ToPort: -1
        IpProtocol: -1
      SecurityGroupIngress:
      - CidrIp: "0.0.0.0/0"
        FromPort: 80
        ToPort: 80
        IpProtocol: 6
      - CidrIp: !Ref MyIp 
        IpProtocol: -1
      VpcId: !Ref VPCID
    
